from __future__ import annotations

import hashlib
from collections.abc import Sequence

from src.fpbench.fingerprint_engine.errors import InvalidTemplateError, TemplateExtractionError
from src.fpbench.fingerprint_engine.types import (
    CandidateResult,
    EngineCapabilities,
    EngineMetadata,
    FingerprintImage,
    FingerprintTemplate,
    GalleryTemplate,
    IdentificationResult,
    MatchResult,
    QualityResult,
)


class NullFingerprintEngine:
    """Deterministic fake engine for tests and architecture validation only."""

    provider_id = "null"
    provider_version = "1.0.0"
    template_format = "fpbench-null-template"
    template_version = "1"
    verification_threshold = 0.75
    quality_threshold = 50.0
    _template_prefix = b"fpbench-null-template-v1:"

    def metadata(self) -> EngineMetadata:
        return EngineMetadata(
            provider_id=self.provider_id,
            provider_version=self.provider_version,
            name="Null fingerprint engine",
            description=(
                "Deterministic non-biometric provider for tests and architecture validation. "
                "It must not be used as a real matcher."
            ),
            available=True,
            template_format=self.template_format,
            template_version=self.template_version,
            capabilities=EngineCapabilities(
                supports_template_extraction=True,
                supports_verification=True,
                supports_identification=True,
                supports_quality=True,
                supports_template_storage=True,
                template_formats=[self.template_format],
                score_range=(0.0, 1.0),
                normalized_score_range=(0.0, 1.0),
            ),
            metadata={"biometric_matcher": False, "deterministic": True},
            warnings=["NullFingerprintEngine is not a biometric matcher."],
        )

    def extract_template(self, image: FingerprintImage) -> FingerprintTemplate:
        source_digest = self._image_digest(image)
        template_bytes = self._template_prefix + source_digest.encode("ascii")
        return FingerprintTemplate(
            provider_id=self.provider_id,
            provider_version=self.provider_version,
            template_format=self.template_format,
            template_version=self.template_version,
            template_bytes=template_bytes,
            image_id=image.image_id,
            quality_score=self._quality_from_digest(source_digest),
            metadata={
                "source_digest": source_digest,
                "source_kind": self._image_source_kind(image),
                "biometric_template": False,
            },
            warnings=["Synthetic template generated by the null provider."],
        )

    def verify(
        self,
        probe_template: FingerprintTemplate,
        candidate_template: FingerprintTemplate,
    ) -> MatchResult:
        self._validate_template(probe_template)
        self._validate_template(candidate_template)

        score = self._similarity(probe_template.template_bytes, candidate_template.template_bytes)
        return MatchResult(
            provider_id=self.provider_id,
            provider_version=self.provider_version,
            score=score,
            normalized_score=score,
            threshold=self.verification_threshold,
            decision=score >= self.verification_threshold,
            latency_ms=0.0,
            metadata={"biometric_matcher": False, "deterministic": True},
            warnings=["NullFingerprintEngine verification is synthetic."],
        )

    def identify(
        self,
        probe_template: FingerprintTemplate,
        gallery: Sequence[GalleryTemplate],
        top_k: int = 10,
    ) -> IdentificationResult:
        self._validate_template(probe_template)
        limit = max(int(top_k), 0)
        scored: list[CandidateResult] = []

        for item in gallery:
            self._validate_template(item.template)
            score = self._similarity(probe_template.template_bytes, item.template.template_bytes)
            scored.append(
                CandidateResult(
                    gallery_id=item.gallery_id,
                    rank=0,
                    score=score,
                    normalized_score=score,
                    threshold=self.verification_threshold,
                    decision=score >= self.verification_threshold,
                    subject_id=item.subject_id,
                    provider_id=self.provider_id,
                    provider_version=self.provider_version,
                    latency_ms=0.0,
                    metadata=dict(item.metadata),
                    warnings=["NullFingerprintEngine candidate score is synthetic."],
                )
            )

        ranked = sorted(scored, key=lambda candidate: (-candidate.score, candidate.gallery_id))
        candidates = [
            CandidateResult(
                gallery_id=candidate.gallery_id,
                rank=index + 1,
                score=candidate.score,
                normalized_score=candidate.normalized_score,
                threshold=candidate.threshold,
                decision=candidate.decision,
                subject_id=candidate.subject_id,
                provider_id=candidate.provider_id,
                provider_version=candidate.provider_version,
                latency_ms=candidate.latency_ms,
                metadata=candidate.metadata,
                warnings=candidate.warnings,
                errors=candidate.errors,
            )
            for index, candidate in enumerate(ranked[:limit])
        ]
        top_candidate = candidates[0] if candidates else None
        return IdentificationResult(
            provider_id=self.provider_id,
            provider_version=self.provider_version,
            candidates=candidates,
            top_candidate=top_candidate,
            threshold=self.verification_threshold,
            decision=bool(top_candidate and top_candidate.decision),
            latency_ms=0.0,
            metadata={
                "biometric_matcher": False,
                "deterministic": True,
                "gallery_size": len(gallery),
                "top_k": limit,
            },
            warnings=["NullFingerprintEngine identification is synthetic."],
        )

    def assess_quality(self, image: FingerprintImage) -> QualityResult:
        digest = self._image_digest(image)
        quality_score = self._quality_from_digest(digest)
        normalized = round(quality_score / 100.0, 6)
        return QualityResult(
            provider_id=self.provider_id,
            provider_version=self.provider_version,
            quality_score=quality_score,
            normalized_score=normalized,
            threshold=self.quality_threshold,
            decision=quality_score >= self.quality_threshold,
            latency_ms=0.0,
            metadata={
                "source_digest": digest,
                "source_kind": self._image_source_kind(image),
                "biometric_quality": False,
            },
            warnings=["NullFingerprintEngine quality is synthetic."],
        )

    def _validate_template(self, template: FingerprintTemplate) -> None:
        if template.provider_id != self.provider_id:
            raise InvalidTemplateError(
                f"Template provider {template.provider_id!r} is not compatible with provider {self.provider_id!r}."
            )
        if template.template_format != self.template_format:
            raise InvalidTemplateError(
                f"Template format {template.template_format!r} is not compatible with {self.template_format!r}."
            )
        if template.template_version != self.template_version:
            raise InvalidTemplateError(
                f"Template version {template.template_version!r} is not compatible with {self.template_version!r}."
            )
        if not template.template_bytes.startswith(self._template_prefix):
            raise InvalidTemplateError("Template bytes do not match the null provider template envelope.")

    def _image_digest(self, image: FingerprintImage) -> str:
        if image.image_bytes is not None:
            return hashlib.sha256(image.image_bytes).hexdigest()
        if image.sha256:
            normalized = image.sha256.strip().lower()
            if normalized:
                if len(normalized) == 64 and all(character in "0123456789abcdef" for character in normalized):
                    return normalized
                return hashlib.sha256(f"sha256:{normalized}".encode("utf-8")).hexdigest()
        if image.path:
            return hashlib.sha256(f"path:{image.path}".encode("utf-8")).hexdigest()
        if image.image_id:
            return hashlib.sha256(f"image_id:{image.image_id}".encode("utf-8")).hexdigest()
        raise TemplateExtractionError("FingerprintImage must include image_bytes, sha256, path, or image_id.")

    def _image_source_kind(self, image: FingerprintImage) -> str:
        if image.image_bytes is not None:
            return "image_bytes"
        if image.sha256:
            return "sha256"
        if image.path:
            return "path"
        if image.image_id:
            return "image_id"
        return "unknown"

    def _quality_from_digest(self, digest: str) -> float:
        value = int(digest[:8], 16)
        return round((value % 10001) / 100.0, 2)

    def _similarity(self, left: bytes, right: bytes) -> float:
        if left == right:
            return 1.0

        left_digest = hashlib.sha256(left).digest()
        right_digest = hashlib.sha256(right).digest()
        distance = sum((left_byte ^ right_byte).bit_count() for left_byte, right_byte in zip(left_digest, right_digest))
        total_bits = len(left_digest) * 8
        return round(1.0 - (distance / total_bits), 6)
